spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=Asia/Shanghai&useSSL=false&nullCatalogMeansCurrent=true
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 60000
      connection-timeout: 30000
      connection-test-query: select 1
      max-lifetime: 60000
      validation-timeout: 3000
      login-timeout: 5
  application:
    name: springDemo
server:
  port: 8080

